/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_FreqMeter
#define HEADER_FreqMeter
/*
htop - FreqMeter.h
(C) 2004-2011 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.

This meter is written by Steffen L. Graf (S.Graf@gsg-elektronik.de).
*/

#include "Meter.h"
#define FREQPATH "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq"
#define MAXPATH "/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq"

extern int FreqMeter_attributes[];

extern MeterClass FreqMeter_class;

#endif
